# Generated by Django 4.1.4 on 2022-12-16 15:34

import KreditCart.views
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=KreditCart.views.generate_unique_object_id, max_length=24, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=45)),
                ('payment_amount', models.FloatField()),
                ('net_discount', models.FloatField()),
                ('bill_amount', models.FloatField()),
                ('taxes', models.JSONField(default=dict)),
                ('order_date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.CharField(default=KreditCart.views.generate_unique_object_id, max_length=24, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('discount', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'order_detail',
                'verbose_name_plural': 'Order Details',
            },
        ),
    ]
